{{ if .Values.terraNfs -}}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "common.fullname" . }}-nfs
spec:
  capacity:
    storage: 50Gi
  storageClassName: terra-helm-nfs
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs.terra.fap.no
    path: /nfs/kubernetes/{{ include "common.fullname" . }}
  mountOptions:
      - "nfsvers=4"
      - "nolock"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "common.fullname" . }}-nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: terra-helm-nfs
  resources:
    requests:
      storage: 50Gi
{{- end }}
