{{- $fullName := include "common.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "common.labels" . | indent 4 }}
    {{ if .Values.useHttpACME -}}
    use-http-solver: "true"
    {{- end }}
  annotations:
{{ include "common.annotations" . | indent 4 }}
spec:
  tls:
  - hosts:
    - {{ .Values.domain }}
    secretName: {{ .Values.domain | replace "." "-"}}-tls
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $fullName }}
            port:
              name: web
