# Default values for common.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

domain: example.fap.no

image:
  repository: invalid
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

readiness: false
liveness: false

useHttpACME: false

container:
  port: 5000
service:
  metrics: false
  type: ClusterIP
  port: 80

metallbService: {}

env: []

terraNfs: {}
configmap: {}
configmapping: {}
# configmap: |
#   config.py: |
#     "testytest"
#
# configmapping:
#   - mountPath: /srv/app/config.py
#     configMapKey: config.py

resources:
  limits:
    cpu: 150m
    memory: 128Mi
  requests:
    cpu: 75m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}
